import { useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface UserManualProps {
  onClose: () => void;
}

const BT = '`';
const BT3 = '```';

const MANUAL_CONTENT = [
  '# WSDL-to-MCP User Manual',
  '',
  'WSDL-to-MCP converts SOAP/WSDL web service definitions into MCP (Model Context Protocol) servers, enabling AI assistants like Claude, Gemini, and ChatGPT to call enterprise SOAP services as tools. Everything runs in your browser — your files never leave your machine.',
  '',
  '---',
  '',
  '## Quick Start',
  '',
  `1. **Upload** your ${BT}.wsdl${BT} and ${BT}.xsd${BT} files (or load from a URL)`,
  '2. **Configure** the endpoint URL, authentication, and SOAP version',
  '3. **Review** the generated TypeScript MCP server code',
  `4. **Download** the project as a ${BT}.zip${BT} and connect it to your AI assistant`,
  '',
  '---',
  '',
  '## Step 1: Upload',
  '',
  'Upload your WSDL and XSD files to parse the SOAP service definition.',
  '',
  '### Supported file types',
  '',
  '| Extension | Description |',
  '|-----------|-------------|',
  `| ${BT}.wsdl${BT} | WSDL service definition (required) |`,
  `| ${BT}.xsd${BT} | XML Schema Definition (optional, for complex types) |`,
  '',
  '### How to upload',
  '',
  '- **Drag & drop** files onto the drop zone',
  '- **Click "Browse"** to select files from your filesystem',
  '- **Load an example** — click one of the built-in example WSDL buttons (Calculator, Weather, etc.)',
  '',
  '### What gets parsed',
  '',
  'The parser extracts:',
  '- **Services** and their ports/bindings',
  '- **Operations** (SOAP actions) with input/output messages',
  '- **Complex types** from inline schemas and imported XSD files',
  '- **Namespaces** for proper SOAP envelope construction',
  '',
  '### Example WSDL structure',
  '',
  `${BT3}xml`,
  '<definitions name="Calculator"',
  '  targetNamespace="http://example.com/calc"',
  '  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">',
  '',
  '  <portType name="CalculatorPortType">',
  '    <operation name="Add">',
  '      <input message="tns:AddRequest"/>',
  '      <output message="tns:AddResponse"/>',
  '    </operation>',
  '  </portType>',
  '',
  '  <binding name="CalculatorBinding" type="tns:CalculatorPortType">',
  '    <soap:binding style="document"',
  '      transport="http://schemas.xmlsoap.org/soap/http"/>',
  '    <operation name="Add">',
  '      <soap:operation soapAction="http://example.com/calc/Add"/>',
  '    </operation>',
  '  </binding>',
  '</definitions>',
  BT3,
  '',
  "After uploading, you'll see a summary showing how many services, port types, and operations were found.",
  '',
  '---',
  '',
  '## Step 2: Configure',
  '',
  'Set the runtime options for your generated MCP server.',
  '',
  '### Configuration options',
  '',
  '| Option | Description | Example |',
  '|--------|-------------|---------|',
  `| **Endpoint URL** | The SOAP service endpoint your MCP server will call | ${BT}https://api.example.com/soap${BT} |`,
  '| **Auth Strategy** | How to authenticate requests | None, Basic Auth, API Key, WS-Security |',
  '| **SOAP Version** | SOAP protocol version | 1.1 (most common) or 1.2 |',
  `| **Tool Naming** | How MCP tool names are generated | ${BT}operationName${BT} or ${BT}serviceName_operationName${BT} |`,
  '',
  '### Authentication strategies',
  '',
  '- **None** — No authentication headers added',
  `- **Basic Auth** — Adds ${BT}Authorization: Basic <base64>${BT} header. Credentials are read from environment variables at runtime.`,
  `- **API Key** — Adds a custom header (e.g., ${BT}X-API-Key${BT}) with a value from an environment variable.`,
  '- **WS-Security** — Adds WS-Security UsernameToken to the SOAP header.',
  '',
  '### Example: Basic Auth configuration',
  '',
  'The generated server reads credentials from environment variables:',
  '',
  `${BT3}bash`,
  'export SOAP_USERNAME="myuser"',
  'export SOAP_PASSWORD="mypassword"',
  'npx tsx src/index.ts',
  BT3,
  '',
  '---',
  '',
  '## Step 3: Review',
  '',
  'Inspect all generated TypeScript files before downloading.',
  '',
  '### What gets generated',
  '',
  '| File | Purpose |',
  '|------|---------|',
  `| ${BT}src/index.ts${BT} | MCP server entry point with tool registration |`,
  `| ${BT}src/soap-client.ts${BT} | SOAP HTTP client with XML serialization |`,
  `| ${BT}src/tools/*.ts${BT} | One file per SOAP operation, with Zod input validation |`,
  `| ${BT}src/types.ts${BT} | Shared TypeScript type definitions |`,
  `| ${BT}src/error-handler.ts${BT} | SOAP fault parsing and error formatting |`,
  `| ${BT}package.json${BT} | Node.js project with all dependencies |`,
  `| ${BT}tsconfig.json${BT} | TypeScript configuration |`,
  '',
  '### Navigating the review',
  '',
  '- **Left panel** — Browse the file tree and operation list',
  '- **Right panel** — View the generated source code with syntax highlighting',
  '- Click any operation to jump to its tool implementation file',
  '',
  '### Example: Generated tool file',
  '',
  'Each SOAP operation becomes an MCP tool like this:',
  '',
  `${BT3}typescript`,
  'server.tool(',
  '  "Add",',
  '  "Performs the Add SOAP operation",',
  '  {',
  '    intA: z.number().describe("First operand"),',
  '    intB: z.number().describe("Second operand"),',
  '  },',
  '  async ({ intA, intB }) => {',
  '    const result = await soapClient.call("Add", { intA, intB });',
  '    return { content: [{ type: "text", text: JSON.stringify(result) }] };',
  '  }',
  ');',
  BT3,
  '',
  '---',
  '',
  '## Step 4: Download',
  '',
  'Download the generated project and set it up locally.',
  '',
  '### What you get',
  '',
  `A ${BT}.zip${BT} file containing a complete Node.js project. After extracting:`,
  '',
  `${BT3}bash`,
  'cd my-mcp-server',
  'npm install',
  'npx tsx src/index.ts',
  BT3,
  '',
  '### Connecting to Claude Desktop',
  '',
  'Add the server to your Claude Desktop config file:',
  '',
  `**macOS:** ${BT}~/Library/Application Support/Claude/claude_desktop_config.json${BT}`,
  `**Windows:** ${BT}%APPDATA%\\\\Claude\\\\claude_desktop_config.json${BT}`,
  '',
  `${BT3}json`,
  '{',
  '  "mcpServers": {',
  '    "my-soap-service": {',
  '      "command": "npx",',
  '      "args": ["tsx", "/absolute/path/to/my-mcp-server/src/index.ts"]',
  '    }',
  '  }',
  '}',
  BT3,
  '',
  'The Download step shows a pre-built config snippet you can copy directly.',
  '',
  '### Connecting to other clients',
  '',
  'Any MCP-compatible client can use the generated server. The server communicates over **stdio** (standard input/output), which is the default MCP transport.',
  '',
  '---',
  '',
  '## Step 5: Test Generation',
  '',
  'Generate regression test scripts to validate your SOAP service independently.',
  '',
  '### Supported test formats',
  '',
  '| Format | Output | Use case |',
  '|--------|--------|----------|',
  `| **pytest** | ${BT}tests/test_*.py${BT} | Python-based API testing |`,
  `| **Postman** | ${BT}collection.json${BT} | Import into Postman for manual/automated testing |`,
  `| **SoapUI** | ${BT}soapui-project.xml${BT} | Enterprise SOAP testing tool |`,
  `| **k6** | ${BT}k6-test.js${BT} | Load testing and performance benchmarks |`,
  '',
  '### What gets tested',
  '',
  'Each test script sends real SOAP requests to your endpoint and validates:',
  '- HTTP response status codes',
  '- Valid XML in the response body',
  '- Expected SOAP envelope structure',
  '- Operation-specific response elements',
  '',
  '---',
  '',
  '## Step 6: Playground (Try It Out)',
  '',
  'Test your generated MCP tools live with any LLM — right in the browser.',
  '',
  '### Choosing an LLM provider',
  '',
  '| Provider | Setup | Notes |',
  '|----------|-------|-------|',
  '| **Anthropic (Claude)** | Enter your API key | Recommended for best tool-use support |',
  '| **OpenAI** | Enter your API key | GPT-4o and later models support tool use |',
  '| **Ollama** | Run Ollama locally on default port | Free, local — no API key needed |',
  '| **llama.cpp** | Run llama-server locally | Free, local — no API key needed |',
  '| **Custom OpenAI-compatible** | Enter base URL + optional API key | Any provider with OpenAI-compatible API |',
  '',
  '### Connection settings',
  '',
  'Configure the SOAP endpoint URL, headers, and CORS proxy settings. These settings persist across sessions.',
  '',
  '### Schema overrides',
  '',
  "Each MCP tool's input schema can be edited inline. This is useful for:",
  '- Fixing types that the parser inferred incorrectly',
  '- Adding descriptions to parameters',
  "- Removing optional fields the LLM doesn't need",
  '',
  'Click **"Edit Schema"** on any tool card to open the JSON editor. Click **"Reset"** to revert to the original.',
  '',
  '### Namespace overrides',
  '',
  'Override the XML namespace URIs used in SOAP envelopes. Useful when:',
  '- The WSDL declares one namespace but the server expects another',
  '- You need to add extra namespace declarations',
  '',
  '### Dry-run mode',
  '',
  'Enable dry-run mode to see the exact SOAP XML that *would* be sent — without actually calling the service. This helps you:',
  '- Verify the XML structure before hitting a real endpoint',
  '- Debug namespace or schema issues',
  '- Test without network access',
  '',
  '### SOAP traffic inspector',
  '',
  'The traffic inspector logs every SOAP request and response. Expand any entry to see:',
  '- **Request XML** — the full SOAP envelope sent to the service',
  '- **Response XML** — the raw response (or error details)',
  '- **Timestamp** and tool name for each call',
  '',
  '### Example chat session',
  '',
  BT3,
  'You: Add 5 and 3',
  '',
  'Assistant: I\'ll call the Add operation with intA=5 and intB=3.',
  '',
  '[Tool call: Add({ intA: 5, intB: 3 })]',
  '[Result: { "AddResult": 8 }]',
  '',
  'The result of adding 5 and 3 is **8**.',
  BT3,
  '',
  '---',
  '',
  '## Troubleshooting',
  '',
  '### CORS errors in the playground',
  '',
  'SOAP services typically do not include CORS headers. When calling them from the browser playground, you will see CORS errors. Solutions:',
  '',
  `1. **Use a CORS proxy** — enter a proxy URL in connection settings (e.g., ${BT}https://cors-anywhere.herokuapp.com/${BT})`,
  '2. **Run the MCP server locally** — download the project and run it with Node.js instead of using the browser playground',
  '3. **Use a browser extension** — temporarily disable CORS for development',
  '',
  '### SOAP faults',
  '',
  'If the SOAP service returns a fault, the tool result will include the fault code and message. Common causes:',
  '',
  '| Fault | Cause | Fix |',
  '|-------|-------|-----|',
  `| ${BT}soap:Client${BT} | Invalid request format | Check schema overrides, verify parameter types |`,
  `| ${BT}soap:Server${BT} | Server-side error | Check the service is running and accessible |`,
  `| ${BT}soap:MustUnderstand${BT} | Unsupported SOAP header | Try switching SOAP version (1.1 vs 1.2) |`,
  '',
  '### Schema parsing errors',
  '',
  'If the parser fails to extract operations:',
  '- Ensure the WSDL file is valid XML',
  '- Upload all referenced XSD files alongside the WSDL',
  `- Check that ${BT}<portType>${BT} elements contain ${BT}<operation>${BT} definitions`,
  '- Verify the WSDL uses document/literal or RPC/literal binding style',
  '',
  '### Timeout errors',
  '',
  'If SOAP calls time out in the playground:',
  '- Verify the endpoint URL is correct and reachable',
  '- Check if a VPN or firewall is blocking the connection',
  '- Try the dry-run mode first to verify the request XML is correct',
  '- If using a CORS proxy, ensure it is running and accessible',
].join('\n');

export function UserManual({ onClose }: UserManualProps) {
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  return (
    <div className="manual-overlay" onClick={(e) => {
      if (e.target === e.currentTarget) onClose();
    }}>
      <div className="manual-content">
        <button className="manual-close-btn" onClick={onClose} aria-label="Close manual">
          &times;
        </button>
        <div className="manual-body">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{MANUAL_CONTENT}</ReactMarkdown>
        </div>
      </div>
    </div>
  );
}
